---
title: "Descriptive and Inferencial statistics"
author: "Ravi Shankar"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


--------------------------------------------------------------------------------------------------------

# Five number summary

```{r concatanation vector, echo=FALSE}
data = c(78,87,23,34,12,80)
summary(data)
```


--------------------------------------------------------------------------------------------------------

# Mean and Standard deviation

```{r}
mean(data)

sd(data)
```


--------------------------------------------------------------------------------------------------------

# Histogram


### Simple histogram with frequency
```{r}
dataset=c(91,49,76,112,97,42,70, 100, 8, 112, 95, 90, 78, 62, 56, 94, 65, 58, 109, 70, 109, 91, 71, 76, 68, 62, 134, 57, 83, 66)

hist(dataset)
```


### Histograms with title, label and density 

```{r}
hist(dataset, 
     xlab = "My data", 
     main = "My histogram", 
     freq = F,
     col = 'pink')

```


### Histograms with density curve line 

```{r}
hist(dataset, 
     xlab = "My data", 
     main = "My histogram", 
     freq = F,
     col = 'pink')
lines(density(dataset), col = 'blue', lwd = 3)
```


### Histograms adjusted bin width

```{r}
hist(dataset, 
     xlab = "My data", 
     main = "My histogram", 
     freq = F,
     col = 'green',
     breaks = 10)
lines(density(dataset), col = 'black', lwd = 3)
```

--------------------------------------------------------------------------------------------------------

# Scatterplot (bivariate data)

```{r}
test_1_score = rnorm(50, 45, 12)
test_2_score = rnorm(50, 40, 15)

plot(test_2_score ~ test_1_score,
     xlab = "Test 1 score",
     ylab = "Test 2 score",
     main = "Test scores",
     col = "blue")

```






